/* CREACION DE UNA TABLA DE EJEMPLO */
CREATE TABLE cliente(cli_id int primary key, nomb_cli varchar(50) not null default '', renta_anual float);

/* CREACION DE LA TABLA DE LOG DONDE EL ID ES AUTOINCREMENTAL */
DROP TABLE IF EXISTS LOG;
CREATE TABLE LOG(id int auto_increment primary key, tabla varchar(25), operacion varchar(50));

/* CREACION LOG PARA LA INSERCION SOBRE CLIENTE*/
drop trigger IF exists LOG_CLIENTE_INSERT;
CREATE TRIGGER LOG_CLIENTE_INSERT after insert ON CLIENTE FOR EACH ROW 
INSERT INTO LOG VALUES('0', 'CLIENTE', 'AÑADO UN REGISTRO NUEVO');
SELECT * FROM LOG;
INSERT INTO cliente VALUES(1, 'cliente 1', 30);
INSERT INTO cliente VALUES(2, 'cliente 2', 13);
SELECT * FROM LOG;

/* CREACION LOG PARA LA ELIMINACION Y ACTUALIZACION SOBRE CLIENTE*/
drop trigger IF exists LOG_CLIENTE_DELETE;
CREATE TRIGGER LOG_CLIENTE_DELETE after delete ON CLIENTE FOR EACH ROW 
INSERT INTO LOG VALUES('0', 'CLIENTE', 'ELIMINO UN REGISTRO EXISTENTE');
drop trigger IF exists LOG_CLIENTE_UPDATE;
CREATE TRIGGER LOG_CLIENTE_UPDATE after update ON CLIENTE FOR EACH ROW 
INSERT INTO LOG VALUES('0', 'CLIENTE', 'MODIFICO UN REGISTRO EXISTENTE');

SELECT * FROM LOG;
DELETE FROM cliente where id='9';
UPDATE cliente SET renta_anual=renta_anual*1.10;
SELECT * FROM LOG;