
show triggers;
SHOW CREATE TRIGGER LOG_CLIENTE_INSERT;

CREATE TRIGGER LOG_CLIENTE_INSERT after insert ON CLIENTE FOR EACH ROW 
INSERT INTO LOG VALUES('0', 'CLIENTE', 'AÑADO UN REGISTRO NUEVO');


DELIMITER //
DROP TRIGGER IF EXISTS  LOG_CLIENTE_INSERT //
CREATE TRIGGER LOG_CLIENTE_INSERT after insert ON CLIENTE FOR EACH ROW 
BEGIN
	INSERT INTO LOG VALUES('0', 'CLIENTE', CONCAT('AÑADO UN REGISTRO NUEVO ', NEW.NOMB_CLI));
END;
//

DELIMITER ;


DELIMITER //
DROP TRIGGER IF EXISTS  LOG_CLIENTE_INSERT //
CREATE TRIGGER LOG_CLIENTE_INSERT after insert ON CLIENTE FOR EACH ROW 
BEGIN
	INSERT INTO LOG VALUES('0', 'CLIENTE', CONCAT('AÑADO UN REGISTRO NUEVO ', NEW.NOMB_CLI));
END;
//

DELIMITER ;

DELIMITER //
DROP TRIGGER IF EXISTS  LOG_CLIENTE_INSERT //
CREATE TRIGGER LOG_CLIENTE_INSERT after insert ON CLIENTE FOR EACH ROW 
BEGIN
   DECLARE vUser varchar(50);
   SELECT USER() INTO vUser;

   INSERT INTO LOG VALUES('0', 'CLIENTE', CONCAT('AÑADO UN REGISTRO NUEVO -', NEW.NOMB_CLI,' - ', SYSDATE(),' - ', vUser));
END; //

DELIMITER ;


DELIMITER //
DROP TRIGGER IF EXISTS  LOG_CLIENTE_INSERT //
CREATE TRIGGER LOG_CLIENTE_INSERT before insert ON CLIENTE FOR EACH ROW 
BEGIN
	DECLARE vUser varchar(50);
	DECLARE msg varchar(255);
    
	SELECT USER() INTO vUser;
    
    IF NOT new.renta_anual < 1000 THEN 
        SET msg='Datos de Renta No validos';
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
    end if;	
   
	IF NEW.renta_anual < 0 THEN
        SET NEW.renta_anual = 0;
	ELSEIF NEW.renta_anual > 100 THEN
        SET NEW.renta_anual = 100;
    END IF;

   INSERT INTO LOG VALUES('0', 'CLIENTE', CONCAT('AÑADO UN REGISTRO NUEVO -', NEW.NOMB_CLI,' - ', SYSDATE(),' - ', vUser));
END; 
//

insert into cliente values (15,'CLIENTE 15', 130);

DELIMITER ;